name: pusher_dart
description: A pure Dart pusher channels client
version: 0.1.0
homepage: https://github.com/indaband/pusher-dart
documentation: https://github.com/indaband/pusher-dart/blob/main/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mocktail: ^0.2.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
