name: pusher_channels
description: A pure Dart pusher channels client
version: 0.5.2
homepage: https://github.com/indaband/pusher_channels
documentation: https://github.com/indaband/pusher_channels/blob/main/README.md

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  test: ^1.25.2
  mocktail: ^1.0.3
  linter: ^1.30.0
  lints: ^3.0.0
