name: pusher_channels
description: A pure Dart pusher channels client
version: 0.1.3
homepage: https://github.com/indaband/pusher_channels
documentation: https://github.com/indaband/pusher_channels/blob/main/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mocktail: ^0.1.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
